import type {AgeBand,Course,Module,Pathway} from "./model";

// `module` is the most readable domain term here; this is not the Node module object.
// eslint-disable-next-line @next/next/no-assign-module-variable
const module=(id:string,title:string,outcome:string,items:[string,"video"|"lettura"|"laboratorio"|"quiz"|"progetto",number,string][]):Module=>({id,title,outcome,lessons:items.map((item,index)=>({id:`${id}-${index+1}`,title:item[0],kind:item[1],minutes:item[2],description:item[3]}))});

export const bands:{id:AgeBand;label:string;short:string;title:string;description:string;symbol:string}[]=[
  {id:"3-5",label:"3–5 anni",short:"Piccoli",title:"Scopro",description:"Storie, suoni e attività da fare insieme a un adulto.",symbol:"●"},
  {id:"6-10",label:"6–10 anni",short:"Primaria",title:"Esploro",description:"Missioni brevi, mappe del sapere e laboratori concreti.",symbol:"✦"},
  {id:"11-13",label:"11–13 anni",short:"Medie",title:"Costruisco",description:"Problemi reali, esperimenti e progetti di gruppo.",symbol:"◇"},
  {id:"14-18",label:"14–18 anni",short:"Superiori",title:"Scelgo",description:"Percorsi disciplinari, orientamento e portfolio.",symbol:"↗"},
  {id:"adulti",label:"18+",short:"Adulti",title:"Trasformo",description:"Competenze, cittadinanza e formazione lungo tutta la vita.",symbol:"∞"},
];

export const courses:Course[]=[
  {id:"mondo-vivo",title:"Il mondo è vivo",subtitle:"Natura, corpo e meraviglia",band:"3-5",subject:"Scoperta",level:"iniziale",weeks:4,color:"yellow",teacher:"Laboratorio Infanzia Aperta",license:"CC BY-SA 4.0",skills:["osservazione","linguaggio","cura"],featured:true,modules:[
    module("mv1","Piccole grandi vite","Riconoscere viventi e non viventi",[["Chi vive qui?","video",6,"Una storia interattiva tra foglie, formiche e sassi."],["Caccia ai colori","laboratorio",15,"Osserva e raccogli cinque colori della natura con un adulto."],["Racconta la scoperta","progetto",10,"Disegna o registra una cosa nuova che hai notato."]]),
    module("mv2","Il corpo racconta","Nominare sensazioni e bisogni",[["Respiro e movimento","video",5,"Un gioco lento per ascoltare il corpo."],["La ruota delle emozioni","laboratorio",12,"Abbina espressioni, colori e parole."],["Cosa ho imparato?","quiz",5,"Una verifica visiva senza voti."]])]},
  {id:"numeri-gioco",title:"Numeri in gioco",subtitle:"Quantità, forme e ritmo",band:"3-5",subject:"Matematica",level:"iniziale",weeks:3,color:"cyan",teacher:"Officina dei Numeri",license:"CC BY 4.0",skills:["quantità","forme","ritmo"],modules:[module("ng1","Contare il quotidiano","Usare i numeri in situazioni familiari",[["Uno, due, tanti","video",5,"Conta oggetti e persone."],["Costruisci una sequenza","laboratorio",15,"Crea un ritmo con forme e colori."],["La mia collezione","progetto",10,"Ordina piccoli oggetti per forma o grandezza."]])]},
  {id:"missione-terra",title:"Missione Terra",subtitle:"Scienze e clima con le mani",band:"6-10",subject:"Scienze",level:"iniziale",weeks:8,color:"lime",teacher:"Collettivo Semi",license:"CC BY-SA 4.0",skills:["metodo scientifico","ecosistemi","cooperazione"],featured:true,modules:[
    module("mt1","Osservare come scienziati","Formulare una domanda verificabile",[["Da domanda a ipotesi","video",9,"Come trasformare la curiosità in ricerca."],["Diario del cielo","laboratorio",25,"Osserva il cielo per sette giorni."],["Controlla l’ipotesi","quiz",8,"Riconosci osservazioni, ipotesi e prove."]]),
    module("mt2","Acqua comune","Comprendere il ciclo e gli usi dell’acqua",[["Il viaggio di una goccia","lettura",12,"Un racconto illustrato sul ciclo dell’acqua."],["Filtro in miniatura","laboratorio",30,"Costruisci un modello con materiali semplici e supervisione."],["Mappa dell’acqua","progetto",45,"Racconta da dove arriva l’acqua del tuo quartiere."]])]},
  {id:"parole-ponti",title:"Parole che fanno ponti",subtitle:"Leggere, raccontare, ascoltare",band:"6-10",subject:"Italiano",level:"iniziale",weeks:6,color:"violet",teacher:"Biblioteca Aperta",license:"CC BY-SA 4.0",skills:["lettura","scrittura","ascolto"],modules:[module("pp1","Storie da molti punti","Cambiare il punto di vista in un racconto",[["Chi racconta?","lettura",12,"Scopri narratore e personaggi."],["La stessa scena, due voci","laboratorio",25,"Riscrivi un episodio da un altro punto di vista."],["Biblioteca di classe","progetto",35,"Crea una piccola antologia condivisa."]])]},
  {id:"codice-comune",title:"Codice comune",subtitle:"Programmazione, dati e reti",band:"11-13",subject:"Tecnologia",level:"iniziale",weeks:10,color:"cyan",teacher:"Officina Digitale Comune",license:"CC BY-SA 4.0",skills:["logica","programmazione","cittadinanza digitale"],featured:true,modules:[
    module("cc1","Pensare per algoritmi","Scomporre un problema in passi",[["Istruzioni senza ambiguità","video",10,"Perché le macchine hanno bisogno di precisione."],["Algoritmo umano","laboratorio",25,"Guida un compagno lungo un percorso."],["Debug della ricetta","quiz",9,"Trova e correggi errori di sequenza."]]),
    module("cc2","Dati, potere e diritti","Comprendere come i dati descrivono le persone",[["Che cosa lascia una traccia","lettura",15,"Dati personali, inferenze e consenso."],["Mappa delle app","laboratorio",35,"Analizza quali dati usano servizi quotidiani."],["Carta dei diritti digitali","progetto",60,"Scrivi regole condivise per una piattaforma scolastica."]])]},
  {id:"storia-quartiere",title:"Storia dal quartiere",subtitle:"Fonti, memoria e territorio",band:"11-13",subject:"Storia",level:"intermedio",weeks:8,color:"yellow",teacher:"Archivio Popolare",license:"CC BY-SA 4.0",skills:["fonti","ricerca","storia orale"],modules:[module("sq1","Una fonte non è la verità","Valutare provenienza e limiti delle fonti",[["Tracce del passato","video",11,"Oggetti, documenti e testimonianze."],["Intervista con consenso","laboratorio",35,"Prepara domande e raccogli una storia."],["Atlante della memoria","progetto",70,"Costruisci una pagina verificata sul territorio."]])]},
  {id:"fondamenti-scientifici",title:"Fondamenti scientifici",subtitle:"Matematica, fisica, chimica e biologia",band:"14-18",subject:"STEM",level:"intermedio",weeks:24,color:"violet",teacher:"Rete Docenti Aperti",license:"CC BY 4.0",skills:["modellazione","laboratorio","analisi dati"],featured:true,modules:[
    module("fs1","Misurare e modellare","Passare dal fenomeno al modello",[["Grandezze e incertezza","video",18,"Misure, errori e cifre significative."],["Pendolo e dati","laboratorio",50,"Raccogli dati e confronta un modello."],["Relazione di laboratorio","progetto",70,"Documenta metodo, dati e conclusioni."]]),
    module("fs2","Materia e trasformazioni","Leggere reazioni e conservazioni",[["Atomi e legami","lettura",22,"Un modello della materia."],["Bilanciare una reazione","laboratorio",35,"Esercizi guidati con feedback."],["Verifica di padronanza","quiz",18,"Controlla concetti e procedure."]])]},
  {id:"democrazia-pratica",title:"Democrazia in pratica",subtitle:"Istituzioni, economia e partecipazione",band:"14-18",subject:"Educazione civica",level:"intermedio",weeks:12,color:"lime",teacher:"Scuola di Cittadinanza",license:"CC BY-SA 4.0",skills:["argomentazione","istituzioni","bilancio"],modules:[module("dp1","Decidere insieme","Confrontare modelli decisionali",[["Regole, potere, responsabilità","video",16,"Come funzionano delega, mandato e controllo."],["Assemblea simulata","laboratorio",55,"Prendi una decisione con regole trasparenti."],["Bilancio partecipato","progetto",90,"Progetta la destinazione di risorse comuni."]])]},
  {id:"dati-per-decidere",title:"Dati per decidere",subtitle:"Dalla tabella a una scelta responsabile",band:"adulti",subject:"Competenze digitali",level:"iniziale",weeks:6,color:"cyan",teacher:"Scuola Pubblica dei Dati",license:"CC BY 4.0",skills:["fogli di calcolo","statistica","decisioni"],featured:true,modules:[
    module("dd1","Domande prima dei numeri","Definire indicatori utili e leggibili",[["Il dato non parla da solo","video",14,"Contesto, campione e confronto."],["Ripulisci un dataset","laboratorio",45,"Correggi formati, duplicati e valori mancanti."],["Nota di decisione","progetto",60,"Raccomanda un’azione dichiarando i limiti."]]),
    module("dd2","Visualizzare senza ingannare","Scegliere una rappresentazione coerente",[["Scale e proporzioni","lettura",18,"Errori comuni nei grafici."],["Dal foglio al grafico","laboratorio",45,"Costruisci tre viste della stessa domanda."],["Revisione tra pari","progetto",35,"Dai e ricevi feedback con una griglia."]])]},
  {id:"italiano-quotidiano",title:"Italiano quotidiano",subtitle:"Lingua per vivere, lavorare e partecipare",band:"adulti",subject:"Lingue",level:"iniziale",weeks:12,color:"yellow",teacher:"Rete Lingua Comune",license:"CC BY-SA 4.0",skills:["comprensione","servizi","lavoro"],modules:[module("iq1","Orientarsi nei servizi","Comprendere e compilare documenti essenziali",[["Parole della città","video",12,"Uffici, trasporti e servizi."],["Leggere un modulo","laboratorio",30,"Riconosci campi e istruzioni."],["La mia pratica","progetto",40,"Prepara una richiesta con dati simulati."]])]},
];

export const pathways:Pathway[]=[
  {id:"scopro-mondo",band:"3-5",eyebrow:"PERCORSO GUIDATO",title:"Scopro il mondo",description:"Un primo viaggio tra natura, numeri, parole, emozioni e movimento.",duration:"12 settimane · con un adulto",courseIds:["mondo-vivo","numeri-gioco"],outcomes:["Osservare e nominare","Giocare con quantità e forme","Raccontare ciò che si scopre"]},
  {id:"esploratori",band:"6-10",eyebrow:"CICLO COMPLETO",title:"Esploratori della conoscenza",description:"Leggere il mondo, sperimentare e condividere ciò che si è imparato.",duration:"1 anno modulare",courseIds:["missione-terra","parole-ponti"],outcomes:["Leggere e comunicare","Usare il metodo scientifico","Collaborare a un progetto"]},
  {id:"costruttori",band:"11-13",eyebrow:"PERCORSO INTERDISCIPLINARE",title:"Costruire, verificare, raccontare",description:"Tecnologia, storia e territorio uniti da progetti reali.",duration:"20 settimane",courseIds:["codice-comune","storia-quartiere"],outcomes:["Programmare una soluzione","Valutare fonti e dati","Documentare un progetto"]},
  {id:"autonomia",band:"14-18",eyebrow:"DIPLOMA APERTO",title:"Conoscenza e autonomia",description:"Fondamenti disciplinari, cittadinanza, orientamento e portfolio verificabile.",duration:"2 anni componibili",courseIds:["fondamenti-scientifici","democrazia-pratica"],outcomes:["Padroneggiare i fondamenti","Argomentare con prove","Costruire un portfolio"]},
  {id:"formazione-continua",band:"adulti",eyebrow:"FORMAZIONE CONTINUA",title:"Competenze per trasformare",description:"Percorsi pratici per il lavoro, la vita quotidiana e la partecipazione.",duration:"Moduli da 4–12 settimane",courseIds:["dati-per-decidere","italiano-quotidiano"],outcomes:["Usare dati e strumenti","Accedere ai servizi","Rendere visibili le competenze"]},
];

export function findCourse(id:string){return courses.find((course)=>course.id===id)}
